
server:
  port: 18002
spring:
  application:
    name: cloud-finchley-consumer
  
http:
  multipart:
    max-file-size: 2000Mb      # Max file size，默认1M
    max-request-size: 2500Mb   # Max request size，默认10M