server:
  port: 19002
spring:
  application:
    name: cloud-finchley-provider
  profiles:
    active: default


# 注：Spring Boot2不能用spring.datasource.schema/data指定初始化SQL脚本，否则与actuator不能共存
# 原因：https://github.com/spring-projects/spring-boot/issues/13042
# https://github.com/spring-projects/spring-boot/issues/13539